# Generated by Django 4.2.6 on 2023-10-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_position_players_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='slug',
        ),
    ]
